version: '3.9'

services:
  frontend:
    build: ./Dockerfile.front
    ports:
      - 443:443
    restart: on-failure

  backend:
    build: ./Dockerfile.back
    ports:
      - 8000:8000
    restart: on-failure

  ML:
    build: ./Dockerfile.ml
    ports:
      - 8001:8001
    restart: on-failure
